cursor #e0def4
cursor_text_color #e0def4

foreground            #e0def4
background            #191724
selection_foreground  #191724
selection_background  #f6c177
url_color             #c4a7e7

color0   #1f1d2e
color1   #ff728c
color2   #73e78d
color3   #ffdb72
color4   #b392db
color5   #4d346a
color6   #c4a7e7
color7   #eae3f2
color8   #908a96
color9   #ff9fb1
color10  #a5ffba
color11  #ffe8a5
color12  #ddc2fe
color13  #e3cdff
color14  #eddfff
color15  #fbf8ff
