[mgr]
show_hidden = true
sort_by = "mtime"
sort_reverse = true

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[plugin]
prepend_previewers = [
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
]

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "Compress with ouch"
