general {
  ignore_dbus_inhibit = false
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
  inhibit_sleep = 3
}

# Heads-up before lock
listener {
  timeout = 290
  on-timeout = notify-send -a "You've been idle for a while now..."
  on-resume = notify-send -a "Welcome back!"
}

# Lock the session
listener {
  timeout = 300
  on-timeout = pidof hyprlock || hyprlock
}

# Turn displays off
listener {
  timeout = 330
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Finally suspend
listener {
  timeout = 1800
  on-timeout = systemctl suspend
}
