source=~/.config/hypr/current-theme.conf

# Omarchy-style minimal lock screen mapped to your palette
$lock_bg = $overlay
$lock_inner = $text
$lock_outer = $iris
$lock_font = $base
$lock_check = $surface

general {
  hide_cursor = true
  enable_fingerprint = true
}

background {
  monitor =
  color = $lock_bg
}

animations {
  enabled = false
}

input-field {
  monitor =
  size = 600, 100
  position = 0, 0
  halign = center
  valign = center

  inner_color = $lock_inner
  outer_color = $lock_outer
  outline_thickness = 4

  font_family = CaskaydiaMono Nerd Font
  font_color = $lock_font

  placeholder_text =  Enter Password 󰈷 
  check_color = $lock_check
  fail_text = <i>$PAMFAIL ($ATTEMPTS)</i>

  rounding = 0
  shadow_passes = 0
  fade_on_empty = false
}

auth {
  fingerprint:enabled = true
}
