exec-once = dbus-update-activation-environment --systemd --all

# Ensure the idle daemon runs so suspend triggers fire
exec-once = systemctl --user start hypridle.service
exec-once = pypr
exec-once = systemctl --user start hyprpolkitagent
exec-once = clipse -listen
exec-once = udiskie
# Notification daemon (Hyprpanel will provide notifications)
#exec-once = mako
exec-once = hyprpanel

# exec-once = hyprlock
# Ensure a Kitty instance is running with a known control socket
exec-once = kitty --listen-on unix:@mykitty --single-instance --start-as=minimized --detach

exec-once = hyprctl dispatch exec "sleep 10s && slack -u"
exec-once = hyprctl dispatch exec "sleep 10s && env GDK_BACKEND=x11 mailspring --ozone-platform=x11 --password-store='gnome-libsecret' --background"
exec-once = hyprctl dispatch exec "sleep 10s && discord --start-minimized"
exec-once = hyprctl dispatch exec "sleep 10s && dropbox"
exec-once = [workspace 1 silent] $browser
exec-once = ~/.config/scripts/code_workspace2.sh
