exec-once = dbus-update-activation-environment --systemd --all

exec-once = pypr
exec-once = systemctl --user start hyprpolkitagent

exec-once = waybar

exec-once = hyprctl dispatch exec "sleep 10s && slack -u"
exec-once = hyprctl dispatch exec "sleep 10s && mailspring --password-store="gnome-libsecret" --background"
exec-once = hyprctl dispatch exec "sleep 10s && discord --start-minimized"
exec-once = hyprctl dispatch exec "sleep 10s && dropbox"
exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] cursor
